Repository braintree/braintree_ios, pull requests merged in 2025-04, with the labels that each got.

#1539 [v7] Updated API Client for SEPA Direct Debit
  CHANGELOG.md
  Demo/Application/Features/SEPADirectDebitViewController.swift
  SampleApps/CarthageTest/CarthageTest/ViewController.swift
  SampleApps/SPMTest/SPMTest/ViewController.swift
  Sources/BraintreeSEPADirectDebit/BTSEPADirectDebitClient.swift
  Sources/BraintreeSEPADirectDebit/SEPADirectDebitAPI.swift
  UnitTests/BraintreeSEPADirectDebitTests/BTSEPADirectDebitClient_Tests.swift
  UnitTests/BraintreeSEPADirectDebitTests/SEPADirectDebitAPI_Tests.swift
  V7_MIGRATION.md
Labels: v7

#1542 Add BTContactPreference
  Braintree.xcodeproj/project.pbxproj
  CHANGELOG.md
  Demo/Application/Features/PayPalWebCheckoutViewController.swift
  Sources/BraintreePayPal/BTContactPreference.swift
  Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
  UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift
Labels: do not merge

#1544 Make `userAuthenticationEmail` optional for all App Switch Flows
  CHANGELOG.md
  Demo/Application/Features/PayPalWebCheckoutViewController.swift
  Sources/BraintreePayPal/BTPayPalCheckoutRequest.swift
  Sources/BraintreePayPal/BTPayPalVaultRequest.swift
  UnitTests/BraintreePayPalTests/BTPayPalCheckoutRequest_Tests.swift
  UnitTests/BraintreePayPalTests/BTPayPalVaultRequest_Tests.swift
Labels: do not merge

#1560 [PRV2] Move existing logic to BTShopperInsightsClientV2
  Braintree.xcodeproj/project.pbxproj
  Sources/BraintreeShopperInsights/BTShopperInsightsClientV2.swift
  UnitTests/BraintreeShopperInsightsTests/BTShopperInsightsClientV2_Tests.swift
Labels: PRV2
